services:
    # api:
    #   build: .
    #   depends_on:
    #     - db
    #     - migration
    #   command: npm run start:prod
    #   ports:
    #     - '5000:5000'
    # migration:
    #   build: .
    #   depends_on:
    #     - db
    #   command: npm run migration:run:prod
    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: 'postgres'
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: '12345'
        volumes:
            - pg-data:/var/lib/postgresql/data
        ports:
            - '5438:5432'
        restart: always
    redis:
        image: redis:latest
        ports:
            - '6379:6379'
        volumes:
            - redis-data:/data
        restart: always
volumes:
    pg-data:
        driver: local
    redis-data:
        driver: local
